# render.yaml
services:
  - type: web
    name: chemokine-viewer
    env: docker
    region: ohio               # pick region near your bucket (us-east-2 = Ohio)
    healthCheckPath: /healthz
    envVars:
      - key: USE_S3
        value: "true"
      - key: S3_BUCKET
        value: goldrath-chemokine-viewer
      - key: DATA_MANIFEST
        value: datasets_manifest.json
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: us-east-2
      - key: MPLBACKEND
        value: Agg
    # Uncomment if you keep .h5ad fallback caching
    # disks:
    #   - name: h5ad-cache
    #     mountPath: /var/cache/h5ad
    #     sizeGB: 10
